name: composer-ai

namespacePrefix: composer-ai-

# Git Repository for the ArgoCD Application
repo:
  url: https://github.com/aokugel/appOfApps.git # Change This on Fork
  branch: elastic-instance

# Namespace for the ArgoCD Application
gitops:
  namespaceSuffix: gitops

# Passing this value to all of the sub-applications to make it so we can dynamically figure out urls
clusterDomain: apps.cluster-w2lh7.w2lh7.sandbox1093.opentlc.com

# Default Values File for the Helm Chart
defaultValuesFile: values.yaml

# Applications to be deployed
applications:
  - name: vllm-model
    path: data-ingestion/vllm
    namespaceSuffix: apps
  - name: weaviate
    path: data-ingestion/weaviate
    namespaceSuffix: apps
    enabled: false
  - name: elasticsearch
    path: data-ingestion/elasticsearch
    namespaceSuffix: apps
  - name: kfp-pipeline
    path: data-ingestion/kfp
    namespaceSuffix: apps
  - name: quarkus-llm-router
    path: chatbot/quarkus-llm-router
    namespaceSuffix: apps
  - name: chatbot-ui
    path: chatbot/chatbot-ui
    namespaceSuffix: apps
    # Add ignoreDifferences to allow deployment to be updated by ImageStream
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/spec/containers/0/image
  - name: mongodb
    path: chatbot/mongodb
    namespaceSuffix: apps
  - name: bootstrap
    path: util/bootstrap
    namespaceSuffix: apps
